#!/usr/bin/env python3
"""Split MySQL develop DDL into simple pre/post deploy phase files.

Develop rule set:
- pre: obvious CREATE statements
- post: DROP, permission/account control, data statements, and ambiguous DDL
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from production.migration_phase_splitter import (  # noqa: E402
    ensure_statement_terminator,
    normalize_for_match,
    split_sql_statements,
    summarize,
)

PHASE_ORDER = ("pre", "post")

PERMISSION_PREFIXES = (
    "GRANT ",
    "REVOKE ",
    "CREATE USER",
    "ALTER USER",
    "DROP USER",
    "RENAME USER",
    "CREATE ROLE",
    "DROP ROLE",
    "SET DEFAULT ROLE",
    "SET PASSWORD",
    "FLUSH PRIVILEGES",
)

DATA_PREFIXES = (
    "INSERT ",
    "REPLACE ",
    "UPDATE ",
    "DELETE ",
    "LOAD DATA ",
)


@dataclass
class Unit:
    source_order: int
    phase: str
    reason: str
    sql: str
    summary: str
    unit_id: str = ""


def classify_statement(sql: str) -> tuple[str, str]:
    text = normalize_for_match(sql)
    if not text:
        return "post", "Only comments or empty SQL is ambiguous in develop mode"

    if text.startswith(PERMISSION_PREFIXES):
        return "post", "Permission/account control is handled after deploy in develop mode"

    if re.match(r"^CREATE\b", text):
        return "pre", "CREATE statement is deploy-before in develop mode"

    if re.match(r"^DROP\b", text):
        return "post", "DROP statement is deploy-after in develop mode"

    if re.search(r"\bDROP\b", text):
        return "post", "Statement contains DROP and is deploy-after in develop mode"

    if text.startswith(DATA_PREFIXES):
        return "post", "Data statement is not split separately in develop mode"

    return "post", "Ambiguous statement is deploy-after in develop mode"


def assign_ids(units: Iterable[Unit]) -> None:
    counters: Counter[str] = Counter()
    for unit in units:
        counters[unit.phase] += 1
        unit.unit_id = f"{unit.phase}-{counters[unit.phase]:03d}"


def group_filename(base: str, phase: str) -> str:
    return f"{base}.{phase}.sql"


def unit_filename(base: str, phase: str, idx: int) -> str:
    return f"{base}.{phase}.{idx:03d}.sql"


def parse_sql_file(source_file: Path) -> list[Unit]:
    raw = source_file.read_text(encoding="utf-8")
    statements = split_sql_statements(raw)

    units: list[Unit] = []
    for i, statement in enumerate(statements, start=1):
        phase, reason = classify_statement(statement)
        units.append(
            Unit(
                source_order=i,
                phase=phase,
                reason=reason,
                sql=statement,
                summary=summarize(statement),
            )
        )
    return units


def write_sql_artifacts(source_file: Path, out_dir: Path, base_name: str, units: list[Unit]) -> dict:
    assign_ids(units)

    phase_groups: dict[str, list[Unit]] = {phase: [] for phase in PHASE_ORDER}
    for unit in units:
        phase_groups[unit.phase].append(unit)

    generated_files: list[str] = []

    for phase in PHASE_ORDER:
        current = phase_groups[phase]
        if not current:
            continue

        phase_path = out_dir / group_filename(base_name, phase)
        lines: list[str] = [
            "-- Auto-generated by develop/migration_phase_splitter.py",
            f"-- source: {source_file}",
            f"-- phase: {phase}",
            f"-- generated_at_utc: {datetime.now(timezone.utc).isoformat()}",
            "",
        ]

        for unit in current:
            lines.extend(
                [
                    f"-- unit: {unit.unit_id}",
                    f"-- source_order: {unit.source_order}",
                    f"-- reason: {unit.reason}",
                    ensure_statement_terminator(unit.sql),
                    "",
                ]
            )

        phase_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        generated_files.append(str(phase_path))

        for idx, unit in enumerate(current, start=1):
            unit_path = out_dir / unit_filename(base_name, phase, idx)
            unit_lines = [
                "-- Auto-generated statement unit",
                f"-- source: {source_file}",
                f"-- unit: {unit.unit_id}",
                f"-- source_order: {unit.source_order}",
                f"-- reason: {unit.reason}",
                "",
                ensure_statement_terminator(unit.sql),
                "",
            ]
            unit_path.write_text("\n".join(unit_lines), encoding="utf-8")
            generated_files.append(str(unit_path))

    phase_counts = {phase: len(phase_groups[phase]) for phase in PHASE_ORDER}

    return {
        "source_file": str(source_file),
        "mode": "develop",
        "total_statements": len(units),
        "phase_counts": phase_counts,
        "units": [
            {
                "id": unit.unit_id,
                "phase": unit.phase,
                "source_order": unit.source_order,
                "reason": unit.reason,
                "summary": unit.summary,
            }
            for unit in units
        ],
        "generated_files": generated_files,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Split SQL migration into develop pre/post phase files."
    )
    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument("--input", dest="source", help="Path to source SQL")
    source_group.add_argument(
        "--forward",
        dest="source",
        help="Alias for --input, kept for consistency with production splitter",
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory (default: <input_dir>/develop_split_migrations)",
    )

    args = parser.parse_args()

    source_path = Path(args.source).expanduser().resolve()
    if not source_path.exists():
        print(f"[error] source SQL not found: {source_path}", file=sys.stderr)
        return 1

    out_dir = (
        Path(args.out_dir).expanduser().resolve()
        if args.out_dir
        else source_path.parent / "develop_split_migrations"
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    base_name = source_path.name
    if base_name.endswith(".sql"):
        base_name = base_name[: -len(".sql")]

    units = parse_sql_file(source_path)
    result = write_sql_artifacts(
        source_file=source_path,
        out_dir=out_dir,
        base_name=base_name,
        units=units,
    )

    manifest = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "out_dir": str(out_dir),
        "result": result,
        "notes": [
            "develop mode has only pre/post phases",
            "CREATE statements are pre-deploy",
            "DROP, permission/account control, data, and ambiguous statements are post-deploy",
        ],
    }

    manifest_path = out_dir / f"{base_name}.manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    print(f"[ok] output directory: {out_dir}")
    print(f"[ok] manifest: {manifest_path}")
    print("[ok] phase counts:", result["phase_counts"])

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
